version: '3'
services:
  api:
    image: node:14
    build: .
    ports:
      - 3030:3030
    volumes:
      - ./src:/var/www/app
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:11
    ports:
      - 55432:5432
    env_file:
      - ./database/env